---
#- stat: path=/etc/php5/apache2/php.ini
#  register: modphp

- stat: path=/etc/php5/fpm/php.ini
  register: php5fpm

- stat: path=/etc/php/7.0/fpm/php.ini
  register: php7fpm

- stat: path=/etc/{{ php_path}}/cli/php.ini
  register: php_cli




- include: php5-fpm.yml
  when: php5fpm.stat.exists

- include: php7-fpm.yml
  when: php7fpm.stat.exists

- include: php-cli.yml
  when: php_cli.stat.exists


#- include: mod-php.yml
#  when: modphp.stat.exists