---
- name: php-cli | Ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/{{ php_path }}/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server_timezone }}'

- name: php-cli | Enabling opcache cli
  lineinfile: dest=/etc/{{ php_path }}/cli/php.ini
              regexp=';?opcache.enable_cli=\d'
              line='opcache.enable_cli=1'